### PR TITLE
Group study README.md commit

### PR DESCRIPTION
**Pull request by tvsirius**
- [ ] Markdown code is correct well-formatted
  - [ ] Spelling and grammar are ok
  - [ ] The Norms make sense to you

### CODE REVIEW

**Comment by tvsirius** [comment]
This is a test PR with our README from Norms, and I see it is doing tests! I did't find where to disable them when creating a Pull Request

**Review by delvor — APPROVED** [review]
Ok

**Comment by JumongEric** [comment]
Anyone with access can merge the pull request

**Comment by tvsirius** [comment]
Do the merge

**Pull request merged**
